services:
  # Local gRPC EDS control-plane
  envoy-xds:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: envoy-xds
    environment:
      EDS_CONFIG_PATH: /config/endpoints.yaml
    ports:
      - "5000:5000"
    volumes:
      - .:/config:rw
    networks:
      - envoy-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Envoy proxy that uses envoy-xds for configuration
  envoy:
    image: envoyproxy/envoy:v1.37.1
    container_name: envoy
    depends_on:
      - envoy-xds
    ports:
      - "10000:10000" # admin interface
      - "8080:8080" # listener port
      - "8081:8081" # foo listener port
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --log-level info
    networks:
      - envoy-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

networks:
  envoy-network:
    driver: bridge
